#ifndef SECTION_COLUMNS_H
#define SECTION_COLUMNS_H

enum SectionColumns {
  SECTION_INDEX = 0,
  SECTION_TITLE = 1,
  SECTION_START_TIME = 2,
  SECTION_END_TIME = 3,
  SECTION_DURATION = 4,
};

#endif  // SECTION_COLUMNS_H
